package com.configcat.integration.matrix

object AndOrMatrix : DataMatrix {
    override val sdkKey: String = "configcat-sdk-1/JcPbCGl_1E-K9M-fJOyKyQ/ByMO9yZNn02kXcm72lnY1A"
    override val data =
        """Identifier;Email;Country;Custom1;mainFeature;dependentFeature;emailAnd;emailOr
##null##;;;;public;Chicken;Cat;Cat
;;;;public;Chicken;Cat;Cat
jane@example.com;jane@example.com;##null##;##null##;public;Chicken;Cat;Jane
john@example.com;john@example.com;##null##;##null##;public;Chicken;Cat;John
a@example.com;a@example.com;USA;##null##;target;Cat;Cat;Cat
mark@example.com;mark@example.com;USA;##null##;target;Dog;Cat;Mark
nora@example.com;nora@example.com;USA;##null##;target;Falcon;Cat;Cat
stern@msn.com;stern@msn.com;USA;##null##;target;Horse;Cat;Cat
jane@sensitivecompany.com;jane@sensitivecompany.com;England;##null##;private;Chicken;Dog;Jane
anna@sensitivecompany.com;anna@sensitivecompany.com;France;##null##;private;Chicken;Cat;Cat
jane@sensitivecompany.com;jane@sensitivecompany.com;england;##null##;public;Chicken;Dog;Jane
jane;jane;##null##;##null##;public;Chicken;Cat;Cat
@sensitivecompany.com;@sensitivecompany.com;##null##;##null##;public;Chicken;Cat;Cat
jane.sensitivecompany.com;jane.sensitivecompany.com;##null##;##null##;public;Chicken;Cat;Cat"""
    override val remoteJson =
        """{
   "p":{
      "u":"https://cdn-global.configcat.com",
      "r":0,
      "s":"wp/t/G2kXSBXcxpSHiS0MV9ua/jmPiNQciQl2KiofTE="
   },
   "s":[
      {
         "n":"Beta Users",
         "r":[
            {
               "a":"Email",
               "c":16,
               "l":[
                  "42419377a50e100e5043bb0cf2f51edf40100fc950812e2ef621ff4230cc7440",
                  "5eb6b039d5eb5e65c14f9f77ae02cc2f569e3a10770c5275b6efc43c42436721"
               ]
            }
         ]
      },
      {
         "n":"Developers",
         "r":[
            {
               "a":"Email",
               "c":16,
               "l":[
                  "e7eee78965dcd30dceef765b03794fbe13192044c7dd241140ab067042dbb917",
                  "793c3a66237dc3ace5d58ff077368833545951ebc4c29259309bb0c42582e170"
               ]
            }
         ]
      }
   ],
   "f":{
      "dependentFeature":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainFeature",
                        "c":0,
                        "v":{
                           "s":"target"
                        }
                     }
                  }
               ],
               "p":[
                  {
                     "p":25,
                     "v":{
                        "s":"Cat"
                     },
                     "i":"993d7ee0"
                  },
                  {
                     "p":25,
                     "v":{
                        "s":"Dog"
                     },
                     "i":"08b8348e"
                  },
                  {
                     "p":25,
                     "v":{
                        "s":"Falcon"
                     },
                     "i":"a6fb7a01"
                  },
                  {
                     "p":25,
                     "v":{
                        "s":"Horse"
                     },
                     "i":"699fb4bf"
                  }
               ]
            }
         ],
         "v":{
            "s":"Chicken"
         },
         "i":"e6198f92"
      },
      "dependentFeatureWithUserCondition":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":16,
                        "l":[
                           "947316bbbba2167afbd3814d3f6b587646d7bc5aca7f3aa02432bebdbf17bf67",
                           "70e863f78cf09a78ee4f5eb18f29d4a9ebee1016a4973625b1ead19ad1386ff9"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Dog"
                  },
                  "i":"ef802e43"
               }
            },
            {
               "c":[
                  {
                     "p":{
                        "f":"mainFeatureWithoutUserCondition",
                        "c":0,
                        "v":{
                           "b":true
                        }
                     }
                  }
               ],
               "p":[
                  {
                     "p":34,
                     "v":{
                        "s":"Cat"
                     },
                     "i":"4a65d6ef"
                  },
                  {
                     "p":33,
                     "v":{
                        "s":"Horse"
                     },
                     "i":"fc3bb22b"
                  },
                  {
                     "p":33,
                     "v":{
                        "s":"Falcon"
                     },
                     "i":"32e0e525"
                  }
               ]
            }
         ],
         "v":{
            "s":"Chicken"
         },
         "i":"472e10f4"
      },
      "dependentFeatureWithUserCondition2":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":16,
                        "l":[
                           "4f9261e69d815dcb4f80597f39955de15f417ba90679fc9b247f03b18283946d",
                           "cb9f65999c1d16661793e270887bc3bcda99d2053737faf11a9ffc03b3963f2e"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Dog"
                  },
                  "i":"78eceed0"
               }
            },
            {
               "c":[
                  {
                     "p":{
                        "f":"mainFeature",
                        "c":0,
                        "v":{
                           "s":"public"
                        }
                     }
                  }
               ],
               "p":[
                  {
                     "p":34,
                     "v":{
                        "s":"Cat"
                     },
                     "i":"72b97d0e"
                  },
                  {
                     "p":33,
                     "v":{
                        "s":"Horse"
                     },
                     "i":"81846c69"
                  },
                  {
                     "p":33,
                     "v":{
                        "s":"Falcon"
                     },
                     "i":"e2f3b509"
                  }
               ]
            },
            {
               "c":[
                  {
                     "p":{
                        "f":"mainFeature",
                        "c":0,
                        "v":{
                           "s":"public"
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Frog"
                  },
                  "i":"cfd56c79"
               }
            }
         ],
         "v":{
            "s":"Chicken"
         },
         "i":"9e8d62c6"
      },
      "emailAnd":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":22,
                        "l":[
                           "4_127aa63815a00ec48882875324035a226eedfec3a6785d5fa25a7924a85c3ad4"
                        ]
                     }
                  },
                  {
                     "u":{
                        "a":"Email",
                        "c":2,
                        "l":[
                           "@"
                        ]
                     }
                  },
                  {
                     "u":{
                        "a":"Email",
                        "c":24,
                        "l":[
                           "20_a215f31a501e2ea8cf2b0bd04b09ddbc3a8e95b18a33df4e7b73e3f0f9859329"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Dog"
                  },
                  "i":"a1393561"
               }
            }
         ],
         "v":{
            "s":"Cat"
         },
         "i":"bdabd589"
      },
      "emailOr":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":22,
                        "l":[
                           "5_6305b8a9a93692f85bca7e25d24d5d55f7e54c5d5e3518281ac72391b3c076fa"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Jane"
                  },
                  "i":"01383bbf"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":22,
                        "l":[
                           "5_9892bda500d2af98d78302a8b21c66558d7af5e60b813ac7d86bc0a24a6a7890"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"John"
                  },
                  "i":"a069dc24"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":22,
                        "l":[
                           "5_d5492107764a64aa36ab7ef0897ad90d58e42bc40a9d349116eed29376bc9283"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Mark"
                  },
                  "i":"d7b02cc0"
               }
            }
         ],
         "v":{
            "s":"Cat"
         },
         "i":"ab0b46ad"
      },
      "mainFeature":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":24,
                        "l":[
                           "21_fc5f667e8d3ca3d70d9d08e0122158bb0ac4ff309796f74e67ffb8875ff56535"
                        ]
                     }
                  },
                  {
                     "u":{
                        "a":"Country",
                        "c":16,
                        "l":[
                           "ca8b73be854eba07330afe5f23d88321d3e244e079f72a8bcffbd621e6efcc97",
                           "7af1edb337f921cc1b10922987a17b1d816be9e0bbb9c20ea1cdd913e7eb5866"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"private"
                  },
                  "i":"64f8e1a6"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Country",
                        "c":16,
                        "l":[
                           "34682b8157c70f7d64240b7dfdeccbc0b991ca18d68cb5c62e9c88f242dba8ed"
                        ]
                     }
                  },
                  {
                     "s":{
                        "s":0,
                        "c":1
                     }
                  },
                  {
                     "s":{
                        "s":1,
                        "c":1
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"target"
                  },
                  "i":"f570ef26"
               }
            }
         ],
         "v":{
            "s":"public"
         },
         "i":"f16ac582"
      },
      "mainFeatureWithoutUserCondition":{
         "t":0,
         "v":{
            "b":true
         },
         "i":"1c6ca36e"
      }
   }
}
"""
}
