package com.configcat.integration.matrix

object PrerequisiteFlagMatrix : DataMatrix {
    override val sdkKey: String = "configcat-sdk-1/JcPbCGl_1E-K9M-fJOyKyQ/JoGwdqJZQ0K2xDy7LnbyOg"
    override val data =
        """Identifier;Email;Country;Custom1;mainBoolFlag;mainStringFlag;mainIntFlag;mainDoubleFlag;stringDependsOnBool;stringDependsOnString;stringDependsOnStringCaseCheck;stringDependsOnInt;stringDependsOnDouble;stringDependsOnDoubleIntValue;boolDependsOnBool;intDependsOnBool;doubleDependsOnBool;boolDependsOnBoolDependsOnBool;mainBoolFlagEmpty;stringDependsOnEmptyBool;stringInverseDependsOnEmptyBool;mainBoolFlagInverse;boolDependsOnBoolInverse
##null##;;;;True;public;42;3.14;Dog;Cat;Cat;Cat;Cat;Cat;True;1;1.1;False;True;EmptyOn;EmptyOn;False;True
;;;;True;public;42;3.14;Dog;Cat;Cat;Cat;Cat;Cat;True;1;1.1;False;True;EmptyOn;EmptyOn;False;True
john@sensitivecompany.com;john@sensitivecompany.com;##null##;##null##;False;private;2;0.1;Cat;Dog;Cat;Dog;Dog;Cat;False;42;3.14;True;True;EmptyOn;EmptyOn;True;False
jane@example.com;jane@example.com;##null##;##null##;True;public;42;3.14;Dog;Cat;Cat;Cat;Cat;Cat;True;1;1.1;False;True;EmptyOn;EmptyOn;False;True"""
    override val remoteJson =
        """{
   "p":{
      "u":"https://cdn-global.configcat.com",
      "r":0,
      "s":"VrjJzqaatxwl8wvjEaKSgGmLI4tqtXWUCWblByPip4M="
   },
   "f":{
      "boolDependsOnBool":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainBoolFlag",
                        "c":0,
                        "v":{
                           "b":true
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"8dc94c1d"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"d6194760"
      },
      "boolDependsOnBoolDependsOnBool":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"boolDependsOnBool",
                        "c":0,
                        "v":{
                           "b":true
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":false
                  },
                  "i":"d6870486"
               }
            }
         ],
         "v":{
            "b":true
         },
         "i":"cd4c95e7"
      },
      "boolDependsOnBoolInverse":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainBoolFlagInverse",
                        "c":1,
                        "v":{
                           "b":true
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"3c09bff0"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"cecbc501"
      },
      "doubleDependsOnBool":{
         "t":3,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainBoolFlag",
                        "c":0,
                        "v":{
                           "b":true
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "d":1.1
                  },
                  "i":"271fd003"
               }
            }
         ],
         "v":{
            "d":3.14
         },
         "i":"718aae2b"
      },
      "intDependsOnBool":{
         "t":2,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainBoolFlag",
                        "c":0,
                        "v":{
                           "b":true
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "i":1
                  },
                  "i":"d2dda649"
               }
            }
         ],
         "v":{
            "i":42
         },
         "i":"43ec49a8"
      },
      "mainBoolFlag":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":24,
                        "l":[
                           "21_551d0379d16ec3df7a3e4f3303366fc74f53b681fdd10e8a0cb526e13694228b"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":false
                  },
                  "i":"e842ea6f"
               }
            }
         ],
         "v":{
            "b":true
         },
         "i":"8a68b064"
      },
      "mainBoolFlagEmpty":{
         "t":0,
         "v":{
            "b":true
         },
         "i":"f3295d43"
      },
      "mainBoolFlagInverse":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":24,
                        "l":[
                           "21_6caa25575aedf0887841fe0abf9aecad51ae78e772ae81733c305596b6d5a8f0"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"28c65f1f"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"d70e47a7"
      },
      "mainDoubleFlag":{
         "t":3,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":24,
                        "l":[
                           "21_1a8f5a5548eedead214f7e3bde8df18edce179d7304c608a2b23573370b996c8"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "d":0.1
                  },
                  "i":"a67947ed"
               }
            }
         ],
         "v":{
            "d":3.14
         },
         "i":"beb3acc7"
      },
      "mainIntFlag":{
         "t":2,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":24,
                        "l":[
                           "21_8f73d9bca2eeb929259cf137d9ab1f17c3808eec5670ee0fa612af6fb0443a31"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "i":2
                  },
                  "i":"67e14078"
               }
            }
         ],
         "v":{
            "i":42
         },
         "i":"a7490aca"
      },
      "mainStringFlag":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Email",
                        "c":24,
                        "l":[
                           "21_860fe91a11ed68bd1f605e4336538136619a3f136f47b6da21cd828f068d2268"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"private"
                  },
                  "i":"51b57fb0"
               }
            }
         ],
         "v":{
            "s":"public"
         },
         "i":"24c96275"
      },
      "stringDependsOnBool":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainBoolFlag",
                        "c":0,
                        "v":{
                           "b":true
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Dog"
                  },
                  "i":"fc8daf80"
               }
            }
         ],
         "v":{
            "s":"Cat"
         },
         "i":"d53a2b42"
      },
      "stringDependsOnDouble":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainDoubleFlag",
                        "c":0,
                        "v":{
                           "d":0.1
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Dog"
                  },
                  "i":"84fc7ed9"
               }
            }
         ],
         "v":{
            "s":"Cat"
         },
         "i":"9cc8fd8f"
      },
      "stringDependsOnDoubleIntValue":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainDoubleFlag",
                        "c":0,
                        "v":{
                           "d":0
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Dog"
                  },
                  "i":"842c1d75"
               }
            }
         ],
         "v":{
            "s":"Cat"
         },
         "i":"db7f56c8"
      },
      "stringDependsOnEmptyBool":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainBoolFlagEmpty",
                        "c":0,
                        "v":{
                           "b":true
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"EmptyOn"
                  },
                  "i":"d5508c78"
               }
            }
         ],
         "v":{
            "s":"EmptyOff"
         },
         "i":"8e0dbe88"
      },
      "stringDependsOnInt":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainIntFlag",
                        "c":0,
                        "v":{
                           "i":2
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Dog"
                  },
                  "i":"12531eec"
               }
            }
         ],
         "v":{
            "s":"Cat"
         },
         "i":"e227d926"
      },
      "stringDependsOnString":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainStringFlag",
                        "c":0,
                        "v":{
                           "s":"private"
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Dog"
                  },
                  "i":"426b6d4d"
               }
            }
         ],
         "v":{
            "s":"Cat"
         },
         "i":"d36000e1"
      },
      "stringDependsOnStringCaseCheck":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainStringFlag",
                        "c":0,
                        "v":{
                           "s":"Private"
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Dog"
                  },
                  "i":"87d24aed"
               }
            }
         ],
         "v":{
            "s":"Cat"
         },
         "i":"ad94f385"
      },
      "stringInverseDependsOnEmptyBool":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "p":{
                        "f":"mainBoolFlagEmpty",
                        "c":1,
                        "v":{
                           "b":true
                        }
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"EmptyOff"
                  },
                  "i":"b7c3efae"
               }
            }
         ],
         "v":{
            "s":"EmptyOn"
         },
         "i":"f6b4b8a2"
      }
   }
}
"""
}
