package com.configcat.integration.matrix

object SegmentsOldMatrix : DataMatrix {
    override val sdkKey: String = "configcat-sdk-1/PKDVCLf-Hq-h-kCzMp-L7Q/y_ZB7o-Xb0Swxth-ZlMSeA"
    override val data =
        """Identifier;Email;Country;Custom1;featureWithSegmentTargeting;featureWithSegmentTargetingCleartext;featureWithNegatedSegmentTargeting;featureWithNegatedSegmentTargetingCleartext;featureWithSegmentTargetingInverse;featureWithSegmentTargetingInverseCleartext;featureWithNegatedSegmentTargetingInverse;featureWithNegatedSegmentTargetingInverseCleartext
##null##;;;;False;False;False;False;False;False;False;False
;;;;False;False;False;False;False;False;False;False
john@example.com;john@example.com;##null##;##null##;True;True;False;False;False;False;True;True
jane@example.com;jane@example.com;##null##;##null##;True;True;False;False;False;False;True;True
kate@example.com;kate@example.com;##null##;##null##;False;False;True;True;True;True;False;False"""
    override val remoteJson =
        """{
   "p":{
      "u":"https://cdn-global.configcat.com",
      "r":0,
      "s":"cRPeZoMoPj/uTPnoDiZhJgUCI4WxJs1P65fNbntr8mY="
   },
   "s":[
      {
         "n":"Beta users",
         "r":[
            {
               "a":"Email",
               "c":16,
               "l":[
                  "b2cde2e3316460a5c0d546b1c31d21d5d1329c559beeeeb2f0adef94db24424b",
                  "e59c6e957433ec7599bb4a53124d2bee8aabf2f05dd3e89aadd993818783b903"
               ]
            }
         ]
      },
      {
         "n":"Beta users (cleartext)",
         "r":[
            {
               "a":"Email",
               "c":0,
               "l":[
                  "jane@example.com",
                  "john@example.com"
               ]
            }
         ]
      },
      {
         "n":"Not Beta users",
         "r":[
            {
               "a":"Email",
               "c":17,
               "l":[
                  "1b0852fa4eb5f205bbb19909c7c6ac6ca809831b14a83ccf3423c247ce429538",
                  "0fa7e84503164cac123153185e9522af87c178e00e4d2b16c2213e526372fdc3"
               ]
            }
         ]
      },
      {
         "n":"Not Beta users (cleartext)",
         "r":[
            {
               "a":"Email",
               "c":1,
               "l":[
                  "jane@example.com",
                  "john@example.com"
               ]
            }
         ]
      }
   ],
   "f":{
      "featureWithNegatedSegmentTargeting":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":0,
                        "c":1
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"772939a0"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"3c0be020"
      },
      "featureWithNegatedSegmentTargetingCleartext":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":1,
                        "c":1
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"0fc9b378"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"6c5f81e3"
      },
      "featureWithNegatedSegmentTargetingInverse":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":2,
                        "c":1
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"145a1eb0"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"e9c52981"
      },
      "featureWithNegatedSegmentTargetingInverseCleartext":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":3,
                        "c":1
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"4898b966"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"fa8f80d5"
      },
      "featureWithSegmentTargeting":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":0,
                        "c":0
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"a49f6150"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"cfe41874"
      },
      "featureWithSegmentTargetingCleartext":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":1,
                        "c":0
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"d03ed88c"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"89fac05a"
      },
      "featureWithSegmentTargetingInverse":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":2,
                        "c":0
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"cf444ba3"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"2ddaee84"
      },
      "featureWithSegmentTargetingInverseCleartext":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":3,
                        "c":0
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"a78fc410"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"6a3224de"
      }
   }
}"""
}
