package com.configcat.integration.matrix

object SegmentMatrix : DataMatrix {
    override val sdkKey: String = "configcat-sdk-1/JcPbCGl_1E-K9M-fJOyKyQ/h99HYXWWNE2bH8eWyLAVMA"
    override val data =
        """Identifier;Email;Country;Custom1;developerAndBetaUserSegment
##null##;;;;False
;;;;False
john@example.com;john@example.com;##null##;##null##;False
jane@example.com;jane@example.com;##null##;##null##;False
kate@example.com;kate@example.com;##null##;##null##;True
""".trimIndent()
    override val remoteJson =
        """{
   "p":{
      "u":"https://cdn-global.configcat.com",
      "r":0,
      "s":"7PsdyG64LeoHUOOkK8Lj8XHEoempVtnbcXrMRGAbjio="
   },
   "s":[
      {
         "n":"Beta Users",
         "r":[
            {
               "a":"Email",
               "c":16,
               "l":[
                  "a85b13a079d912c5cfd7710d838dea1cd95c470edb34808b663f90c8e655f59f",
                  "05329bebdadfddff03be5acd344eac08ebe32343bbed6c48da3d3b682f24f72f"
               ]
            }
         ]
      },
      {
         "n":"Developers",
         "r":[
            {
               "a":"Email",
               "c":16,
               "l":[
                  "8ea8349bbb949c2ddbc69111a2276e3d05d9fdcf26d8f9e5f7cb3f8f110c39ea",
                  "a547454b065be96a0a2e0b0398e05a524d08d70e73a2551d852cd273b48f9dbd"
               ]
            }
         ]
      },
      {
         "n":"Not Beta Users",
         "r":[
            {
               "a":"Email",
               "c":17,
               "l":[
                  "ac3fe8c42300e7dfab453fc5372f9243aa35aeada22e4a1ab9857492e36be977",
                  "8a468dcce2bbe3c0b1336ec672c79786734277d9a5eab62f5f998b12cb42a494"
               ]
            }
         ]
      },
      {
         "n":"Not Developers",
         "r":[
            {
               "a":"Email",
               "c":17,
               "l":[
                  "256303dba70677de7b1a284cbc524cdb7725df3d87936d42a291f9811150e8d5",
                  "83bbef514b6f4ebd0588743784dd4258a28f95d5d4318df24a3730e7fad663b0"
               ]
            }
         ]
      },
      {
         "n":"Not States",
         "r":[
            {
               "a":"Country",
               "c":3,
               "l":[
                  "States"
               ]
            }
         ]
      },
      {
         "n":"United",
         "r":[
            {
               "a":"Country",
               "c":2,
               "l":[
                  "United"
               ]
            }
         ]
      }
   ],
   "f":{
      "countrySegment":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":5,
                        "c":0
                     }
                  },
                  {
                     "s":{
                        "s":4,
                        "c":0
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"A"
                  },
                  "i":"9b7e6414"
               }
            }
         ],
         "v":{
            "s":"Z"
         },
         "i":"f71b6d96"
      },
      "developerAndBetaUserSegment":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":1,
                        "c":0
                     }
                  },
                  {
                     "s":{
                        "s":0,
                        "c":1
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"ddc50638"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"6427f4b8"
      },
      "notDeveloperAndNotBetaUserSegment":{
         "t":0,
         "r":[
            {
               "c":[
                  {
                     "s":{
                        "s":2,
                        "c":0
                     }
                  },
                  {
                     "s":{
                        "s":3,
                        "c":1
                     }
                  }
               ],
               "s":{
                  "v":{
                     "b":true
                  },
                  "i":"77081d42"
               }
            }
         ],
         "v":{
            "b":false
         },
         "i":"a14eaf13"
      }
   }
}""".trimIndent()
}
