package com.configcat.integration.matrix

object SemanticMatrix : DataMatrix {
    override val sdkKey: String = "configcat-sdk-1/PKDVCLf-Hq-h-kCzMp-L7Q/iV8vH2MBakKxkFZylxHmTg"
    override val data =
        """Identifier;Email;Country;Custom1;isOneOf;isOneOfWithPercentage;isNotOneOf;isNotOneOfWithPercentage;lessThanWithPercentage;relations
##null##;;;;Default;Default;Default;Default;Default;Default
id1;;;0.0.0;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );< 1.0.0;< 1.0.0
id1;;;0.1.0;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );< 1.0.0;< 1.0.0
id1;;;0.2.1;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );< 1.0.0;< 1.0.0
id1;;;1;Default;80%;Default;80%;20%;Default
id2;;;1.0;Default;80%;Default;80%;80%;Default
id3;;;1.0.0;Is one of (1.0.0);is one of (1.0.0);Default;80%;80%;<=1.0.0
id4;;;1.0.0.0;Default;80%;Default;20%;20%;Default
id5;;;1.0.0.0.0;Default;80%;Default;80%;80%;Default
id6;;;1.0.1;Default;80%;Is not one of (1.0.0, 3.0.1);Is not one of (1.0.0, 3.0.1);80%;Default
id7;;;1.0.11;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );20%;Default
id8;;;1.0.111;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id9;;;1.0.2;Default;20%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id10;;;1.0.3;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id11;;;1.0.4;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id12;;;1.0.5;Default;20%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id13;;;1.1.0;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id14;;;1.1.1;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id15;;;1.1.2;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id16;;;1.1.3;Default;20%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );20%;Default
id17;;;1.1.4;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );20%;Default
id18;;;1.1.5;Default;20%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id19;;;1.9.0;Default;20%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;Default
id20;;;1.9.99;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );20%;Default
id21;;;2.0.0;Default;80%;Is not one of (1.0.0, 3.0.1);Is not one of (1.0.0, 3.0.1);20%;>=2.0.0
id22;;;2.0.1;Is one of (   , 2.0.1, 2.0.2,    );80%;Is not one of (1.0.0, 3.0.1);Is not one of (1.0.0, 3.0.1);80%;>2.0.0
id23;;;2.0.11;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );20%;>2.0.0
id24;;;2.0.2;Is one of (   , 2.0.1, 2.0.2,    );80%;Is not one of (1.0.0, 3.0.1);Is not one of (1.0.0, 3.0.1);80%;>2.0.0
id25;;;2.0.3;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;>2.0.0
id26;;;3.0.0;Is one of (3.0.0);80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;>2.0.0
id27;;;3.0.1;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );20%;>2.0.0
id28;;;3.1.0;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;>2.0.0
id28;;;3.1.1;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;>2.0.0
id29;;;5.0.0;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );80%;>2.0.0
id30;;;5.99.999;Default;80%;Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    );20%;>2.0.0"""
    override val remoteJson =
        """{
   "p":{
      "u":"https://cdn-global.configcat.com",
      "r":0,
      "s":"ckQuggJzKXlXnTu55hP6Ttabx2elF0NW2rQYsBX0leg="
   },
   "f":{
      "isNotOneOf":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":5,
                        "l":[
                           "1.0.0",
                           "1.0.1",
                           "2.0.0",
                           "2.0.1",
                           "2.0.2"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    )"
                  },
                  "i":"a8d5f278"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":5,
                        "l":[
                           "1.0.0",
                           "3.0.1"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is not one of (1.0.0, 3.0.1)"
                  },
                  "i":"54ac757f"
               }
            }
         ],
         "v":{
            "s":"Default"
         },
         "i":"f79b763d"
      },
      "isNotOneOfWithPercentage":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":5,
                        "l":[
                           "1.0.0",
                           "1.0.1",
                           "2.0.0",
                           "2.0.1",
                           "2.0.2"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is not one of (1.0.0, 1.0.1, 2.0.0   , 2.0.1, 2.0.2,    )"
                  },
                  "i":"9bf9e66f"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":5,
                        "l":[
                           "1.0.0",
                           "3.0.1"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is not one of (1.0.0, 3.0.1)"
                  },
                  "i":"bfc1a544"
               }
            }
         ],
         "p":[
            {
               "p":20,
               "v":{
                  "s":"20%"
               },
               "i":"68f652f0"
            },
            {
               "p":80,
               "v":{
                  "s":"80%"
               },
               "i":"b8d926e0"
            }
         ],
         "v":{
            "s":"Default"
         },
         "i":"b9614bad"
      },
      "isOneOf":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "1.0.0",
                           "2"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is one of (1.0.0, 2)"
                  },
                  "i":"1e934047"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "1.0.0"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is one of (1.0.0)"
                  },
                  "i":"44342254"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "2.0.1",
                           "2.0.2"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is one of (   , 2.0.1, 2.0.2,    )"
                  },
                  "i":"90e3ef46"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "3......"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is one of (3......)"
                  },
                  "i":"59523971"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "3...."
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is one of (3...)"
                  },
                  "i":"2de217a1"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "3..0"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is one of (3..0)"
                  },
                  "i":"bf943c79"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "3.0"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is one of (3.0)"
                  },
                  "i":"3a6a8077"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "3.0."
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is one of (3.0.)"
                  },
                  "i":"44f25fed"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "3.0.0"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"Is one of (3.0.0)"
                  },
                  "i":"e77f5306"
               }
            }
         ],
         "v":{
            "s":"Default"
         },
         "i":"c4ec4d53"
      },
      "isOneOfWithPercentage":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":4,
                        "l":[
                           "1.0.0"
                        ]
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"is one of (1.0.0)"
                  },
                  "i":"0ac4afc1"
               }
            }
         ],
         "p":[
            {
               "p":20,
               "v":{
                  "s":"20%"
               },
               "i":"e25dba31"
            },
            {
               "p":80,
               "v":{
                  "s":"80%"
               },
               "i":"8c70c181"
            }
         ],
         "v":{
            "s":"Default"
         },
         "i":"a94ff896"
      },
      "lessThanWithPercentage":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":6,
                        "s":"1.0.0"
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"\u003C 1.0.0"
                  },
                  "i":"0c27d053"
               }
            }
         ],
         "p":[
            {
               "p":20,
               "v":{
                  "s":"20%"
               },
               "i":"3b1fde2a"
            },
            {
               "p":80,
               "v":{
                  "s":"80%"
               },
               "i":"42e92759"
            }
         ],
         "v":{
            "s":"Default"
         },
         "i":"0081c525"
      },
      "relations":{
         "t":1,
         "r":[
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":6,
                        "s":"1.0.0,"
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"\u003C1.0.0,"
                  },
                  "i":"21b31b61"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":6,
                        "s":"1.0.0"
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"\u003C 1.0.0"
                  },
                  "i":"db3ddb7d"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":7,
                        "s":"1.0.0"
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"\u003C=1.0.0"
                  },
                  "i":"aa2c7493"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":8,
                        "s":"2.0.0"
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"\u003E2.0.0"
                  },
                  "i":"5e47a1ea"
               }
            },
            {
               "c":[
                  {
                     "u":{
                        "a":"Custom1",
                        "c":9,
                        "s":"2.0.0"
                     }
                  }
               ],
               "s":{
                  "v":{
                     "s":"\u003E=2.0.0"
                  },
                  "i":"99482756"
               }
            }
         ],
         "v":{
            "s":"Default"
         },
         "i":"c6155773"
      }
   }
}"""
}
