name: Kotlin SDK Test

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
      - name: Cache Konan
        uses: ./.github/actions/cache-konan
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle
      - name: Run all tests
        run: ./gradlew allTests --stacktrace
        shell: bash
      - name: Archive results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
      - name: Cache Konan
        uses: ./.github/actions/cache-konan
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle
      - name: Run format check
        run: ./gradlew ktlintCheck --stacktrace
        shell: bash